package templates

const EnumTemplate = `// Code generated by ggenums; DO NOT EDIT.
package {{.Package}}

import (
    "encoding/json"
    "fmt"
)

type {{.Type}}Enum string

const (
    {{range .Values -}}
    {{$.Type}}{{.ConstantName}} {{$.Type}}Enum = "{{.StringValue}}"
    {{end}}
)

var All{{.Type}}s = []{{.Type}}Enum{
    {{range .Values -}}
    {{$.Type}}{{.ConstantName}},
    {{end}}
}

func (e {{.Type}}Enum) String() string {
    return string(e)
}

func (e {{.Type}}Enum) Validate() error {
    switch e {
    case {{range $i, $v := .Values}}{{if $i}}, {{end}}{{$.Type}}{{$v.ConstantName}}{{end}}:
        return nil
    default:
        return fmt.Errorf("invalid {{.Type}}: %s", e)
    }
}

func Parse{{.Type}}(s string) ({{.Type}}Enum, error) {
    e := {{.Type}}Enum(s)
    if err := e.Validate(); err != nil {
        return "", err
    }
    return e, nil
}

func (e {{.Type}}Enum) MarshalJSON() ([]byte, error) {
    if err := e.Validate(); err != nil {
        return []byte("null"), nil
    }
    return json.Marshal(string(e))
}

func (e *{{.Type}}Enum) UnmarshalJSON(data []byte) error {
    var s string
    if err := json.Unmarshal(data, &s); err != nil {
        return err
    }

    parsed, err := Parse{{.Type}}(s)
    if err != nil {
        return err
    }

    *e = parsed
    return nil
}
`
